name: Experiment
# on: [push]
on: repository_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test that action
    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ github.event }}
