name: Test
on:
  push: { branches: master }

jobs:
  test:
    name: Matrix test
    runs-on: ubuntu-latest
    strategy:
      matrix: { ruby: ['2.4', '2.5', '2.6', '2.7', '3.0'] }

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Do something with the matrix value
      run: echo Doing it with with ${{ matrix.ruby }}
