name: Experiment
# on: [push]
on: 
  push:
    tags: [deploy*]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test that action
    steps:
    - uses: actions/checkout@v2

    - name: Debug
      run: echo ref: ${{ github.ref }}

    - name: Deploy all
      if: endsWith(github.ref, 'tags/deploy')
      run: echo deploying everything!

    - name: Deploy one
      if: endsWith(github.ref, 'tags/deploy-one')
      run: echo deploying one!
