name: Test
# on: push
on: deployment

jobs:
  main:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pretend to deploy
      run: echo Deploying everything
