name: Laravel

on: pull_request

jobs:
  laravel-checks:
    runs-on: ubuntu-latest
    container: 
      image: thomasowow/laravel-php:7.4
      options: "--entrypoint /bin/bash"

    steps:
    - uses: actions/checkout@v2
    - name: Yarn
      run: yarn
