name: Test
on:
  push: { branches: master }

jobs:
  test:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: |
        git checkkout -b temp
        touch hello
        git add . --all
        git commit -am "commit by github actions"
        git push --set-upstream origin temp
