name: Experiment

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug
      run: |
        export TAG=${GITHUB_REF##*/}
        export TAG_MESSAGE=$(git tag $TAG -ln --format %(contents))
        echo "TAG_MESSAGE = $TAG"
        echo "TAG_MESSAGE = $TAG_MESSAGE"
