name: Experiment
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test that action

    env:
      HOST: example.com

    steps:
    # - uses: actions/checkout@v2

    - env:
        URL: ${{ env.HOST }}/foo.html
      run: echo $URL

