name: Test
on: [push]

jobs:
  main:
    name: Rush demo
    runs-on: ubuntu-latest

    steps:
    - name: Install rush
      run: bash <(curl -s https://raw.githubusercontent.com/DannyBen/rush-cli/master/setup)

    - name: Connect to rush repository
      run: rush clone dannyben/rush-repo-template --name default

    - name: Run a sample script from the repo
      run: rush get hello
