name: Experiment
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test that action

    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-env name=GIT_TAG::${GITHUB_REF/refs\/tags\//}
    - env:
        IMAGE: ${{ env.GIT_TAG }}
      run: echo "tag is $IMAGE"

    - env:
        HOST: example.com
        URL: ${{ env.HOST }}/foo.html
      run: echo "url is $URL"

