name: Test
on: [push]

jobs:
  main:
    name: Rush demo
    runs-on: ubuntu-latest

    steps:
    - name: Install rush
      run: bash <(curl -s https://raw.githubusercontent.com/DannyBen/rush-cli/master/setup)

    - name: Connect to rush repository
      run: rush clone dannyben/rush-repo --name default

    - name: Install RVM
      run: rush get rvm && source "/etc/profile.d/rvm.sh"

    - name: Install Ruby 2.3
      run: rvm install 2.3
