name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Debug

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run some remote script
      run: .github/remote-run dannyben/actions-debug say-hello Thor

    - name: Run another remote script
      run: .github/remote-run dannyben/actions-debug touch-file

    - name: Verify the file was created
      run: ls

