name: Experiment

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug
      run: echo "Tag = ${GITHUB_REF##*/}"
      run: echo "Tag Message = `git tag 1.2.3 -ln --format %(contents)`"
