name: Caching Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Enable Cache
      id: test-cache
      uses: actions/cache@v2
      with:
        path: my-cache
        key: ${{ runner.os }}-my-cache

    - name: Use or generate the cache
      if: steps.test-cache.outputs.cache-hit != 'true'
      run: mkdir test-cache && touch test-cache/hello

    - name: Verify we have our cached file
      run: ls test-cache
