name: Experiment
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test that action

    steps:
    - uses: actions/checkout@v2
    - name: Debug
      env: 
        TEST: ${{ secrets.TEST }}
      run: env

