name: Redis test
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '6.10.3'
