name: Test
on: [push]

jobs:
  test:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: ./build.sh

    - name: Also, do we have yarn?
      run: yarn --version
