name: Experiment
on: [push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Sleep and Run
      run: |
        echo "Sleeping for 10"
        sleep 10
        echo "Donw sleeping"

  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Dependant
      run: |
        echo "Completed dependant job 2"
