name: Experiment
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test that action

    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-env name=GIT_TAG::${GITHUB_REF/refs\/tags\//}
    - env:
        IMAGE: ${{ env.GIT_TAG }}
      run: echo "tag is $IMAGE"

    - env:
        HOST: example.com
        URL1: ${{ env.HOST }}/foo.html
        URL2: ${{ HOST }}/foo.html
        URL3: ${HOST}/foo.html
        URL4: $HOST/foo.html
      run: env | grep URL

