name: Experiment
# on: [push]
on: repository_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test that action
    steps:
    - uses: actions/checkout@v2
    - name: Debug
      run: |
        echo type: ${{ github.event.type }}
        echo event_type: ${{ github.event.event_type }}
        echo client_payload.app: ${{ github.event.client_payload.app }}
        echo app: ${{ github.event.app }}
