name: Test
on: [push]

jobs:
  main:
    name: Rush demo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache gem dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with: { ruby-version: '${{ matrix.ruby }}' }

    - name: Bundle install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
