name: Test
on:
  push:
    tags: ['*']

jobs:
  test:
    name: Matrix test
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    - name: Checkout code
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ github.repository }}

    - name: Test
      run: ls
