name: Test
on: [push]

jobs:
  main:
    name: Rush demo
    runs-on: ubuntu-latest

    steps:
    - name: Install rush
      run: bash <(curl -s https://raw.githubusercontent.com/DannyBen/rush-cli/master/setup)

    - name: Connect to rush repository
      run: rush clone dannyben/rush-repo --name default

    - name: Install Ruby
      run: |
        sudo snap install ruby --classic --channel=2.3/stable
        sudo snap refresh
        eval `ruby.env`
        ruby --version