name: Test
on:
  push: { branches: master }

jobs:
  test:
    name: Matrix test
    runs-on: ubuntu-latest
    strategy:
      matrix: { ruby: ['2.4', '2.5'] }

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

