name: Experiment
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Secret exposure test
      uses: mxschmitt/action-tmate@v2
      env:
        DEBUG_PASSWORD: ${{ secrets.DEBUG_PASSWORD }}

