name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Debug

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Setup Ruby
    #   uses: actions/setup-ruby@v1
    #   with: { ruby-version: '2.6' }

    - name: Setup PATH
      run: echo "::add-path::$PWD"

    - name: Debug
      run: |
        echo $PATH
        test.sh


