name: Test
on:
  push: { branches: master }

jobs:
  test:
    name: Matrix test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Git Tag
      run: echo "{GIT_TAG}=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Build, tag, and push image to Amazon ECR
      env:
        IMAGE_TAG: ${{ env.GIT_TAG }}
      run: |
        echo tag is: $IMAGE_TAG
