name: Experiment
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test that action
    steps:
    - uses: actions/checkout@v2

    - name: Debug
      run: |
        echo ref: ${{ github.ref }}

    - name: Deploy
      if: endsWith(github.ref, 'deploy')
      run: echo deploying!
