name: Debug
on: [push]

jobs:
  debug:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.05

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with: 
        ruby-version: '2.7'

    - name: Run tests
      run: ruby test.rb
