name: Laravel

on: [push]

jobs:
  laravel-checks:
    runs-on: ubuntu-latest
    container: 
      image: thomasowow/laravel-php:7.4
      options: "--entrypoint /bin/bash"

    steps:
    - name: Yarn
      run: yarn
