name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Debug

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rush
      run: bash <(curl -s https://raw.githubusercontent.com/DannyBen/rush-cli/master/setup)

    - name: Connect to rush repository
      run: rush clone dannyben/rush-repo --name default

    - name: Install a rush package
      run: rush get gotop

    - name: Verify the package was installed
      run: gotop --version

