name: Experiment
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test that action

    steps:
    - name: Extract Git Tag
      run: echo ::set-env name=GIT_TAG::${GITHUB_REF/refs\/tags\//}

    - name: Echo git tag
      run: echo "Git tag is $GIT_TAG"
